services:
  app:
    image: ghcr.io/jadikuli/server-arcanumai:1.0
    container_name: arcanum-app
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: arcanum-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: arcanum
      MYSQL_USER: arcanum_user
      MYSQL_PASSWORD: arcanum_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db_data:
